### ISSUE TITLE
Could not register DID (after 6 tries to contact EBSI)!

### ISSUE THREAD

**Issue by fmerg** [walt-id/waltid-ssikit#133]
DID registration to the EBSI fails although previous steps (onboarding and auth-api flow) complete successfully with a valid token:

```commandline
# ./ssikit.sh key gen
...
Key "a7faf423f89447f6ab3d23af62dbbc5e" generated.
#
# ./ssikit.sh did create -m ebsi -k a7faf423f89447f6ab3d23af62dbbc5e
...
DID created: did:ebsi:zoNeMQWP5MrBeANEQaa58pY
...
#
# ./ssikit.sh essif onboard --did did:ebsi:zoNeMQWP5MrBeANEQaa58pY data/bearer-token.txt
...
ESSIF onboarding for DID did:ebsi:zoNeMQWP5MrBeANEQaa58pY was performed successfully.
#
# ./ssikit.sh essif auth-api --did did:ebsi:zoNeMQWP5MrBeANEQaa58pY
...
EBSI Authentication API flow for DID did:ebsi:zoNeMQWP5MrBeANEQaa58pY was performed successfully.
# ./ssikit.sh essif did register --did did:ebsi:zoNeMQWP5MrBeANEQaa58pY
...
Could not register DID (after 6 tries to contact EBSI)!
```

The above is from a Debian machine where the project has been locally built with `./ssikit.sh build` (no containers). Same behaviour when running from outside the container with `docker run -itv $(pwd)/data:/app/data waltid/ssikit`. Do I miss something?

**Comment by waltkb** [comment]
EBSI itself is still in a fairly experimental phase, so it might happen that you have to wait for a few minutes/hours until something is fixed in the EBSI backend by them.

Please try it again later and comment if it still doesn't work.

**Comment by fmerg** [comment]
Problem persists (trying repeatedly since weeks). Would help to know if others can reproduce it or it is a problem of mine. Note however that I've built both ways the project on two different Debian machines.

**Comment by philpotisk** [comment]
@fmerg Thanks for raising this issue. We will look into it.

FYI: We just solved a related issue in the web-wallet, as the did:ebsi registration had an issue there. It is working already on the test-system here https://wallet.waltid.org, and will be deployed next week to the demo-system: https://wallet.walt.id

**Comment by philpotisk** [comment]
Dear @fmerg I was just following this tutorial and the did:ebsi registration was working fine https://docs.walt.id/usage-examples/usage-examples-1/onboarding-and-dids

I realized that you did not create a ECDSA Secp256k1 key, which is mandatory for the registration to work. Please use this command in you first line: ./ssikit.sh key gen **-a Secp256k1**

**Comment by fmerg** [comment]
Hi @philpotisk, it works for Secp256k1. Thank you for pointing this out.
