### ISSUE TITLE
Could not register DID (after 6 tries to contact EBSI)!

### ISSUE THREAD

**Issue by robertbob987** [walt-id/waltid-ssikit#168]
I was  following this tutorial and the did:ebsi registration is not work.

[root@baustem ebsi]# ssikit essif did register --did did:ebsi:zgNnvDuBntqiA7eWPZ52HEn#af5dd2f235bd4707bbe2d13fb0ae9f6c
walt.id SSI Kit 1.11.0-SNAPSHOT (running on Java 17.0.2+8-86)

EBSI ledger registration for DID did:ebsi:zgNnvDuBntqiA7eWPZ52HEn#af5dd2f235bd4707bbe2d13fb0ae9f6c running...

Could not register DID (after 6 tries to contact EBSI)!

**Comment by philpotisk** [comment]
@robertbob987 thanks for reporting this issue. We experienced similar issues in the past. Back then there were due to system downtime or to API updates. We will investigate and see what is causing this error this time.

**Comment by philpotisk** [comment]
@robertbob987 I just tried and it seems to be working

![image](https://user-images.githubusercontent.com/55081379/192502030-75935854-b1a0-4fba-926e-77211b6ce65f.png)

please run the command with "-v" to get more debug info:  ./ssikit.sh **-v** essif onboard data/ebsi/bearer.txt --did did:ebsi:zvL6AmVtkezoHPjvwW8RSTQ

**Comment by philpotisk** [comment]
Dear @robertbob987, I just tried for myself and it is working: 
![image](https://user-images.githubusercontent.com/55081379/192502938-a5e51dc1-0a66-4fe0-9274-1d225ffbc5b4.png)

May I ask you to run the command with the "-v" parameter in order to get additional debug logs? e.g.: ./ssikit.sh **-v** essif did register --did did:ebsi:zvL6AmVtkezoHPjvwW8RSTQ

**Comment by philpotisk** [comment]
@robertbob987 by looking again at your command I see, that you are using the DID AND the keyId. You should not use the keyId, which is the identifier behind the "#":

ssikit essif did register --did did:ebsi:zgNnvDuBntqiA7eWPZ52HEn**#af5dd2f235bd4707bbe2d13fb0ae9f6c**

Please get rid of that part and try again ;-)

**Comment by robertbob987** [comment]
thanks



                           鲍海兵

北京邦天信息技术有限公司
Baustem Information Technologies Co.,Ltd 
北京市海淀区知春路23号量子银座908室
Unit 908, Quantum Silver Plaza, No.23 Zhichun Road, Haidian District, Beijing
Tel:(10)-82351078        Email: ***@***.***@baustem.com
手机：13810545796
 
From: philpotisk
Date: 2022-09-27 18:34
To: walt-id/waltid-ssikit
CC: robertbob987; Mention
Subject: Re: [walt-id/waltid-ssikit] Could not register DID (after 6 tries to contact EBSI)! (Issue #168)
@robertbob987 by looking again at your command I see, that you are using the DID AND the keyId. You should not use the keyId, which is the identifier behind the "#":
ssikit essif did register --did did:ebsi:zgNnvDuBntqiA7eWPZ52HEn**#af5dd2f235bd4707bbe2d13fb0ae9f6c**
Please get rid of that part and try again ;-)
