### ISSUE TITLE
I was directly used the docker image, but not find the idp-config.json

### ISSUE THREAD

**Issue by robertbob987** [walt-id/waltid-ssikit#169]
I was directly used the docker image, but not find the idp-config.json
docker pull waltid/idpkit
docker run -p 8080:8080 -e WALTID_DATA_ROOT=/data -v $PWD:/data waltid/idpkit run
docker exec -it 4b /bin/bash
root@4b4a9b59736e:/waltid-idpkit# ls
bin  data  lib	service-matrix.properties  signatory.conf

**Comment by severinstampler** [comment]
The config files are located in the config subfolder of the data root.
In your case you mounted the current directory into /data of the container. So you should find the config files in /data/config.

**Comment by robertbob987** [comment]
root@iotg-monitore-server-a2c3:~# docker container ls
CONTAINER ID   IMAGE              COMMAND                  CREATED          STATUS          PORTS                                       NAMES
df690b990d72   waltid/walletkit   "/waltid-walletkit/b…"   5 minutes ago    Up 5 minutes    0.0.0.0:8082->8082/tcp, :::8082->8082/tcp   elastic_booth
62429b05c162   waltid/idpkit      "/waltid-idpkit/bin/…"   13 minutes ago   Up 13 minutes   0.0.0.0:8081->8081/tcp, :::8081->8081/tcp   peaceful_clarke
root@iotg-monitore-server-a2c3:~# docker exec -it 62 /bin/sh
# su root
root@62429b05c162:/waltid-idpkit# ls
bin  data  lib	service-matrix.properties  signatory.conf
root@62429b05c162:/waltid-idpkit# cd data
root@62429b05c162:/waltid-idpkit/data# ls
did  ebsi  key	vc
root@62429b05c162:/waltid-idpkit/data# cd ..
root@62429b05c162:/waltid-idpkit# ls
bin  data  lib	service-matrix.properties  signatory.conf
root@62429b05c162:/waltid-idpkit# cd ..
root@62429b05c162:/# ls
bin  boot  data  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var  waltid-idpkit
root@62429b05c162:/# cd data
root@62429b05c162:/data# ls
CloudResetPwdUpdateAgent  bin	data  etc   initrd.img	    lib    lost+found  mnt  proc  run	snap  swapfile	tmp  var      vmlinuz.old
CloudrResetPwdAgent	  boot	dev   home  initrd.img.old  lib64  media       opt  root  sbin	srv   sys	usr  vmlinuz
root@62429b05c162:/data#

**Comment by robertbob987** [comment]
I can't find it

**Comment by severinstampler** [comment]
When you execute the docker run command like you showed, you mount your current directory into /data of the container. So whatever you have in your local directory is mounted into the container. Obviously the config subfolder with the config files should be on your local machine, where you can edit them according to your needs.
I assumed you run the command from the git project root folder. If not, then you need to create that folder and place the config files there before you launch the container.

**Comment by robertbob987** [comment]
I directly use the docker image from docker hub, docker pull waltid/idpkit; then run comand"alias waltid-idpkit="docker run -p 8080:8080 -e WALTID_DATA_ROOT=/data -v $PWD:/data waltid/idpkit"" and "waltid-idpkit run"

**Comment by robertbob987** [comment]
I am not running the git clone to get source code,and run docker build command "docker build --rm -t waltid/idpkit ."

**Comment by severinstampler** [comment]
Copy the config file from https://github.com/walt-id/waltid-idpkit/tree/main/config on your local machine, in a config subfolder. From the parent folder execute the docker command and the files should be there.

**Comment by robertbob987** [comment]
thanks
