### ISSUE TITLE
How to configure the nextcloud openid back end connect IDP? 

### ISSUE THREAD

**Issue by robertbob987** [walt-id/waltid-ssikit#170]
How to configure the nextcloud openid back end connect IDP?

**Comment by robertbob987** [comment]
idp-config.json
Does "externalUrl" refer to the server address of the NEXTCLOUD?

**Comment by robertbob987** [comment]
Could give me a configuration example?
how to configure the nextcloud openid back end connect IDP

**Comment by severinstampler** [comment]
In idp-config.json, you don't configure anything related to NEXTCLOUD.
The IDPKit has no awareness of nextcloud.
I'm not familiar with nextcloud, but I do assume the configuration will be similar to other applications:
* Create a client_id and client_secret (Client registration)
* configure the endpoints of the idpkit on nextcloud
* enter client_id and client_secret and choose authentication method client_secret_basic

**Comment by severinstampler** [comment]
> idp-config.json Does "externalUrl" refer to the server address of the NEXTCLOUD?

No, it refers to the URL by which the IDP Kit is available to external clients.
