### ISSUE TITLE
Build for ARM

### ISSUE THREAD

**Issue by teodem** [walt-id/waltid-ssikit#171]
I am trying to build on my Mac M1. I am experiencing several problems. When I run the build script I get:

```
* What went wrong:
Unable to calculate the value of the task ':compileJava' property 'javaCompiler'.
> Unable to download a toolchain that matches these requirements: {languageVersion=16, vendor=any, implementation=vendor-specific}
   > Unable to download the toolchain. This may indicate that the combination (version, architecture, release/early access, ...) for the required JDK is not available.
      > Could not read 'https://api.adoptium.net/v3/binary/latest/16/ga/mac/aarch64/jdk/hotspot/normal/eclipse' because it does not exist.
```

I installed the arm-specific JDK and removed JDE

```
Matching Java virtual machines (2):
    19 (arm64) "Oracle Corporation" - "Java SE 19" /Library/Java/JavaVirtualMachines/jdk-19.jdk/Contents/Home
    17.0.4 (arm64) "Amazon.com Inc." - "Amazon Corrected 17" /Users/Library/Java/JavaVirtualMachines/corrected-17.0.4.1/Contents/Home
/Library/Java/JavaVirtualMachines/jdk-19.jdk/Contents/Home
```

I can't figure out why I keep getting the error. I guess it's due to the arm architecture, but I don't know how to fix it. Any ideas?

**Comment by taminobaumann** [comment]
Hey @teodem, 

thanks for reaching out! 

On my Mac M1, I don't have any issues building the project.

**My java version:**
<img width="585" alt="Screenshot 2022-10-03 at 11 22 30" src="https://user-images.githubusercontent.com/48290617/193543543-a88b455d-1317-42ba-9b3c-6a86ca0d9d23.png">


**Building the project**

When I build the project, I always use, when I'm inside the project dir: `./ssikit.sh -h` 
"The first time you run the command you will be asked to built the project. You can confirm the prompt"

See full list: https://docs.walt.id/v/ssikit/getting-started/cli-command-line-interface

**Comment by teodem** [comment]
Hi @taminobaumann 

Thank you for your comment. Yes actually i was following the documentation and i start doing the build. But exactly here i get this error. As far as i see, something is not ok with the JDK in my case. I've installed the proper arm version but if i run `cat `which java` | file -` I get: 
```
/dev/stdin: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64eMach-O 64-bit executable arm64e]
(null) (for architecture x86_64):
```
So in my opinion this could cause the problem, or?

**Comment by teodem** [comment]
Update: 
after a clear installation of Java and JDK i still get the same error as before. 
Just for reference my version is: 
```
openjdk version "1.8.0_342"
OpenJDK Runtime Environment Corretto-8.342.07.3 (build 1.8.0_342-b07)
OpenJDK 64-Bit Server VM Corretto-8.342.07.3 (build 25.342-b07, mixed mode)
```

**Comment by taminobaumann** [comment]
I've used the [Oracle website](https://www.oracle.com/java/technologies/downloads/) to download my version.
<img width="796" alt="Screenshot 2022-10-04 at 15 05 07" src="https://user-images.githubusercontent.com/48290617/193826615-1ad44443-8e8b-49e1-be46-acf6447417bf.png">

Otherwise, you could try to run it from `MainCli.kt` from IntelliJ IDEA

**Comment by waltkb** [comment]
1.8 is too old. Please use a release like [jdk-17.0.5+8](https://github.com/adoptium/temurin17-binaries/releases/tag/jdk-17.0.5%2B8) in the flavour macOS / aarch64 from -> https://adoptium.net/temurin/releases
macOS ARM64 builds should be working as of the latest commit.
