### ISSUE TITLE
Docker build

### ISSUE THREAD

**Issue by grafandreas** [walt-id/waltid-ssikit#184]
Hi all,

the walt.id home page states that the SSI kit can be built by just invoking docker. However, this seems to result in an error:

Invoking docker build -t ssikit . results in

 => ERROR [walt-build 2/3] RUN ./gradlew clean build                                                               0.2s
------
 > [walt-build 2/3] RUN ./gradlew clean build:
#18 0.221 /bin/sh: 1: ./gradlew: not found
------
executor failed running [/bin/sh -c ./gradlew clean build]: exit code: 127

Regards,

Andreas

**Comment by philpotisk** [comment]
Hi Andreas, this is weird, as the mentioned missing file is present in the root of the project. I also tried the Docker build which is working fine for me on Linux. May I ask on which system you are running the Docker build? Please also make sure that you have pulled the latest updates from GitHub. thx.

**Comment by grafandreas** [comment]
Got it, I am building on Windows, but there are no .gitattributes, so the file got converted to CR/LF on clone and is then copied verbatim into the image. That makes it unexecutable. Changed the line endings to Unix and reran -> sucess.

**Comment by philpotisk** [comment]
Great that you could solve the first issue :clap: 

Please tell us the error-log. Actually half of our team are using Windows, so the project definitely should work there.

**Comment by grafandreas** [comment]
Fixed it. The .pem files in test resources had CR/LF, too. Changing it to Unix newlines fixed it. docker build runs through.

**Comment by philpotisk** [comment]
@grafandreas Sounds great. Please also don't hesitate to open a PR with the fixes you have done. thx
