### ISSUE TITLE
Unable to onboard EBSI did after importing DID from a file

### ISSUE THREAD

**Issue by ivan-garcia-euipo** [walt-id/waltid-ssikit#193]
After importing a DID from a file through the CLI tool and executing essif onboard command, an exception is raised "Could not find key". Apparently, the root cause for this issue is that an alias for the did + "#" + kid is created in the did create command but not in the did import method.

**Comment by philpotisk** [comment]
If you import a DID, only the public key is imported. For the EBSI onboarding you would also need the corresponding private key. 
If you create the DID with the CLI tool, a fresh keypair will be created which will work for the EBSI onboarding flow.

**Comment by philpotisk** [comment]
@ivan-garcia-euipo Thanks for pointing out this issue and for fixing it in here https://github.com/walt-id/waltid-ssikit/pull/194
