### ISSUE TITLE
VC Verification With Dynamic Policies 

### ISSUE THREAD

**Issue by taminobaumann** [walt-id/waltid-ssikit#202]
**Error with dynamic policy**
![Markup on 2022-12-12 at 10:43:00](https://user-images.githubusercontent.com/48290617/207013104-1fd2de26-24e3-46ce-9f04-9c35fcfdb158.png)

![Markup on 2022-12-12 at 10:42:12](https://user-images.githubusercontent.com/48290617/207012921-d573eedc-e31e-416f-b1a4-2dc1e44aebbf.png)

**Comment by severinstampler** [comment]
Hi
What is the `ssikit` command alias translating into? 
If it is the `docker run ...` command, I presume the local folder isn't mounted as a volume in the container, and therefore, the rego file isn't found at the `src/...` location.
best regards
Severin
