### ISSUE TITLE
some w3c credential properties should support array or single value

### ISSUE THREAD

**Issue by severinstampler** [walt-id/waltid-ssikit#205]

**Comment by severinstampler** [comment]
The generic verifiable credential supports pre-defined properties, that comply with the W3C specification.
Some of these properties must support array or single value, but currently support only single value.
e.g.: `proof` and `credentialSchema` are such pre-defined properties.

**Comment by ctueck** [comment]
I'm working on switching our DEQAR (generic & EBSI) VC issuer from using the Core API to the Signatory API and have an issue as a result of that, too.

In our case we actually need multi-subject VCs, i.e. where the `credentialSubject` is an array. As far as I can see, the W3C specification allows that, even if it might be a rare use case.

(In our case, these are joint programme accreditations, joint institutional audits or similar: a single accreditation covering several universities, hence each university would be one subject.)
