### ISSUE TITLE
Improve abstraction for VC template management

### ISSUE THREAD

**Issue by tdiesler** [walt-id/waltid-ssikit#210]
Currently, the VcTemplateManager is a singleton, which loads it's templates from the resource class loader,  which in turn does not allow to limit the set of supported templates.

This could be improved by making this thing a service. 
Clients can then swap in their own impl of a `VcTemplateService` to suit their needs.

**Comment by tdiesler** [comment]
I'll try to suggest something

**Comment by tdiesler** [comment]
PR: https://github.com/walt-id/waltid-ssikit/pull/212

**Comment by tdiesler** [comment]
This PR is still pending, is there an issue with it?

**Comment by waltkb** [comment]
2b5e35f
