### ISSUE TITLE
VC template configuration

### ISSUE THREAD

**Issue by waltkb** [walt-id/waltid-ssikit#215]
Currently when importing a VC template some attributes like "issuer" are hardcoded, while in practice credentials may contain the issuer as nested object e.g. `"issuer": { "id": "did:key:..." }`, or a custom object, e.g. `"issuer": { "id": "did:key:...", "name": "Abc" }`.
Currently, this object will simply be overriden with a single string in the merging data provider.

It should be possible to override the JSON paths where the attributes are read from as a configuration objects in the template/import endpoint.

**Comment by philpotisk** [comment]
Currently we support the issuer to be a single attribute or a nested object, where the issuer DID will be used as "id". This seems to be sufficient for the time being.
