### ISSUE TITLE
[SSIKit] Support ebsi v4 api

### ISSUE THREAD

**Issue by mikeplotean** [walt-id/waltid-ssikit#298]
- [ ] did registry -> insertDidDocument method (https://api-pilot.ebsi.eu/docs/apis/did-registry/latest#/operations/post-did-registry-v4-jsonrpc#insertdiddocument)

**Comment by elenaizaguirre** [comment]
Hi @mikeplotean, are you working on update ALL APIs version?

**Comment by mikeplotean** [comment]
hi @elenaizaguirre, the purpose is to update the APIs that are currently used by SSIKit and required for EBSI onboarding / authentication / did-registration, potentially adding others as well. However, the progress on this is paused at the moment.

**Comment by elenaizaguirre** [comment]
ok thanks @mikeplotean

**Comment by cre8** [comment]
@mikeplotean do you know if a lot has to be changed? If not, I would try to update it to the latest EBSI version since some people told me it's not working right now (haven't checked it myself yet)

**Comment by mikeplotean** [comment]
@cre8 currently the lib is rewritten and won't be part of ssikit anymore, but thanks for the offer.

**Comment by mikeplotean** [comment]
moved to ebsi-lib
