### ISSUE TITLE
walt.id OIDC API at 127.0.0.1:7010 not responding

### ISSUE THREAD

**Issue by FilippoScaramuzza** [walt-id/waltid-ssikit#364]
I just built and executed the ssi-kit with `./ssikit.sh serve`. This is the output I got:
```
walt.id Core API:      http://127.0.0.1:7000
 walt.id Signatory API: http://127.0.0.1:7001
 walt.id Custodian API: http://127.0.0.1:7002
 walt.id Auditor API:   http://127.0.0.1:7003
 walt.id ESSIF API:     http://127.0.0.1:7004
 walt.id OIDC API:      http://127.0.0.1:7010
```  
All the APIs work, except for the walt.id OIDC API at http://127.0.0.1:7010. 
I tried to look at the code and apparently it is not fully implemented yet as it is just offering two not-documented apis (`/vc` and `/ci`). Here is the file I looked at : [OidcAPI.kt](https://github.com/walt-id/waltid-ssikit/blob/a533315d1239271d53e7715bf10381cfd9259633/src/main/kotlin/id/walt/rest/oidc/OidcAPI.kt#L16)
Is it a work-in-progress feature? If it is, why is the API exposed?

**Comment by ahmedsmiai** [comment]
Hey @FilippoScaramuzza, The `/` route at [](http://127.0.0.1:7010/) does not exist, Therefore, attempting to access this URL will result in a "not found" error. 
However, you can still interact with the functionality that is available. The code provides two APIs, /ci for credential issuance and /vp for credential presentation. You can make use of tools like curl or make REST calls accordingly.
