### ISSUE TITLE
Create did:web for other domains

### ISSUE THREAD

**Issue by ctueck** [walt-id/waltid-ssikit#51]
Small feature request: would be great if SSIkit could easily create did:web's for other domains than yours.

(I did manage for testing purposes with changing a DID document to another domain, but it also required some manual changes in your SQLite database, so it's a bit hack-ish. ;))

**Comment by philpotisk** [comment]
I fully agree that this important feature is missing for did:web. Due to other priorities did:web was not too much in the focus. So thanks for the reminder at this point! We will now happily solve this issue asap.

**Comment by ctueck** [comment]
Thanks also, works nicely here.
