### ISSUE TITLE
Own private key deleted after verifying self-issued VC

### ISSUE THREAD

**Issue by ctueck** [walt-id/waltid-ssikit#67]
Private key was deleted from key store/DB after we verified a VC on the same instance that issued it.

(Only with `did:ebsi`, probably resolving the own DID accidentally deletes private key.)

**Comment by philpotisk** [comment]
I tried to reproduce the issue, but it didn't happen in my case.

Anyway, I have now added a safty-check so that keys after resolving DIDs are not replaced. Maybe this would solve your issue. Please let me know your results. thx

**Comment by philpotisk** [comment]
I extended the ESSIF integration-test, where an EBSI DID is registered and a VC issued and verified. After the verification there is now an additional check if the private key is still in the key-store https://github.com/walt-id/waltid-ssikit/blob/faf6db6ead087dc8f7a4c3da812408851d4cb260/src/test/kotlin/id/walt/essif/EssifIntTest.kt#L191 As this integration test passes successfully, I will close this issue now.

**Comment by ctueck** [comment]
Sorry, took a while, but I tried a few more times and wasn't able to reproduce it again either. I only managed to reproduce it once, shortly before writing you/filing this, but the problem is I can't recall on which codebase this was...

Is it possible that https://github.com/walt-id/waltid-ssikit/commit/53404d260ad58c8deab532ab017fcb5cd5ea277b#diff-ebdca7051630e72d7cc7c0f22ebbb6468e36f63f2ad74d353e09bef4217a2048L361 actually fixed the issue?

(At least the first occurrence pre-dates that commit.)
